CREATE TABLE STUDENTS (
	ID VARCHAR(50) PRIMARY KEY,
	NAME TEXT NOT NULL,
	EMAIL TEXT UNIQUE NOT NULL,
	PHONE_NO TEXT CHECK (LENGTH(PHONE_NO)=10),
	PROFILE_PIC TEXT,
	PASSWORD TEXT CHECK (LENGTH(PASSWORD) >= 6),
	USER_ROLE TEXT DEFAULT 'student',
	IS_VERIFIED BOOLEAN default true,
	VERIFICATION_CODE TEXT,
    AUTH_ID VARCHAR(255) UNIQUE,
	ADDRESS VARCHAR(50) UNIQUE,
	FOREIGN KEY (ADDRESS) REFERENCES ADDRESSES (ID) ON DELETE SET NULL
);

CREATE TABLE ADDRESSES (
	ID VARCHAR(50) PRIMARY KEY,
	COUNTRY TEXT NOT NULL,
	STATE TEXT NOT NULL,
	CITY TEXT NOT NULL,
	PIN_CODE TEXT NOT NULL
);

CREATE TABLE COURSES (
	ID VARCHAR(50) PRIMARY KEY,
	TITLE TEXT NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	THUMBNAIL TEXT NOT NULL,
	PRICE NUMERIC NOT NULL DEFAULT 0,
	CREATED_DATE DATE DEFAULT CURRENT_DATE,
	IS_PUBLISHED BOOLEAN DEFAULT FALSE,
	INSTRUCTOR_ID VARCHAR(50) NOT NULL,
	FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR (ID)
);

CREATE TABLE INSTRUCTOR (
	ID VARCHAR(50) PRIMARY KEY,
	NAME TEXT NOT NULL,
	EMAIL TEXT UNIQUE NOT NULL,
	PROFILE_PIC TEXT,
	PASSWORD TEXT CHECK (LENGTH(PASSWORD) >= 6),
	USER_ROLE TEXT DEFAULT 'instructor',
	IS_VERIFIED BOOLEAN ,
	VERIFICATION_CODE TEXT,
	AUTH_PROVIDER VARCHAR(50),
    AUTH_ID VARCHAR(255) UNIQUE,
	ABOUT TEXT,
	EXPERIENCE TEXT,
	PROFILE_STATUS BOOLEAN DEFAULT FALSE,
);

CREATE TABLE COURSES_TAGS (
	ID VARCHAR(50) PRIMARY KEY,
	TAGS VARCHAR(50) NOT NULL,
	COURSE_ID VARCHAR(50) NOT NULL,
	FOREIGN KEY(COURSE_ID) REFERENCES COURSES(ID)
);

CREATE TABLE REVIEWS (
	ID VARCHAR(50) PRIMARY KEY,
	STUDENT_ID VARCHAR(50) NOT NULL,
	COURSE_ID VARCHAR(50) NOT NULL,
	REVIEW TEXT,
	POINTS NUMERIC NOT NULL CHECK (POINTS >= 1 AND POINTS <= 5),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID),
	FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID)
);

CREATE TABLE COURSES_PROGRESS (
	ID VARCHAR(50) PRIMARY KEY,
	PERCENTAGE_COMPLETED NUMERIC DEFAULT 0,
	STUDENT_ID VARCHAR(50) NOT NULL,
	ENROLLED_COURSE VARCHAR(50) NOT NULL,
	COMPLETED_MODULES INTEGER[] DEFAULT NULL,
	FOREIGN KEY(STUDENT_ID) REFERENCES STUDENTS (ID),
	FOREIGN KEY (ENROLLED_COURSE) REFERENCES ENROLLED_COURSES(ID)
);

CREATE TABLE ENROLLED_COURSES (
	ID VARCHAR(50) PRIMARY KEY,
	COURSE_ID VARCHAR(50) NOT NULL,
	STUDENT_ID VARCHAR(50) NOT NULL,
	FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID)
);

CREATE TABLE STUDENT_CART(
	ID VARCHAR(50) PRIMARY KEY,
	STUDENT_ID VARCHAR(50) NOT NULL,
	COURSE_ID VARCHAR(50) NOT NULL UNIQUE,
	FOREIGN KEY (COURSE_ID) REFERENCES COURSES (ID),
	FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS (ID)
)

